image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - pip install -r requirements.txt
  - pytest

deploy_pypi:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload  dist/*
  only:
    - tags
